spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/web_truyen??useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB


server:
  port: 8000
minio:
  endpoint: localhost
  port: 9000
  accessKey: minio
  secretKey: minio123
  secure: false
  bucket-name: truyen
  image-size: 10485760
  file-size: 1073741824


